### ISSUE TITLE
inconsistent units in radolan showcase

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib-notebooks#16]
Some units in the radolan showcase (and possibly other notebooks) are inconsistent. RY for instance is in "mm/5min" "not mm/h".

**Comment by heistermann** [comment]
I think the unit for RY is just `mm`. I am quite certain it is not `mm/h`. Using `mm/5min` is rather to calrify the accumulation interval.

**Comment by kmuehlbauer** [comment]
Sure, so what is needed to get it all consistent?

**Comment by heistermann** [comment]
Grr, just trying to find the product overview in the web.

**Comment by kmuehlbauer** [comment]
https://docs.wradlib.org/en/stable/notebooks/radolan/radolan_showcase.html

**Comment by heistermann** [comment]
No, I mean from DWD.

**Comment by kmuehlbauer** [comment]
https://www.dwd.de/DE/leistungen/radolan/radolan_info/radolan_radvor_op_komposit_format_pdf.pdf?__blob=publicationFile&v=5

**Comment by heistermann** [comment]
No, there used to be a pdf that also specified the units for all products in a table.

**Comment by kmuehlbauer** [comment]
https://www.dwd.de/DE/leistungen/radolan/produktuebersicht/radolan_produktuebersicht_pdf.pdf?__blob=publicationFile&v=6

**Comment by heistermann** [comment]
Exactly, thank you!

**Comment by kmuehlbauer** [comment]
Another one: https://www.dwd.de/DE/leistungen/radolan/radarniederschlagsprodukte/radar_produkt%C3%BCbersicht.pdf?__blob=publicationFile&v=2

**Comment by heistermann** [comment]
Yes, but from 2009...

**Comment by heistermann** [comment]
Anyway, I guess [this](https://www.dwd.de/DE/leistungen/radolan/produktuebersicht/radolan_produktuebersicht_pdf.pdf?__blob=publicationFile&v=6) is the basis to specify the units.

**Comment by kmuehlbauer** [comment]
So, it is `mm/5min` for `RY`.

**Comment by heistermann** [comment]
Yes.

**Comment by heistermann** [comment]
Ha, and now I get your actual point.

**Comment by heistermann** [comment]
I thought you wanted to channge from `mm/5min` to `mm/h`.

**Comment by heistermann** [comment]
But it is the other way around.

**Comment by kmuehlbauer** [comment]
Yes, this was somehow misleading

**Comment by heistermann** [comment]
Maybe we should introduce the unit in the overview table unter section [National Composites](https://docs.wradlib.org/en/stable/notebooks/radolan/radolan_showcase.html#RADOLAN-Composite).
