### ISSUE TITLE
Fix external links

### ISSUE THREAD

**Issue by kmuehlbauer** [wradlib/wradlib-notebooks#19]
- external links should point to the most recent endpoint (eg. matplotlib)

**Comment by cemysf** [comment]
what do you mean by that?

**Comment by kmuehlbauer** [comment]
@cemysf There are hyperlinks in the notebooks, which point to old targets. One example is in https://github.com/wradlib/wradlib-notebooks/blob/master/notebooks/visualisation/wradlib_plot_curvelinear_grids.ipynb.

There are links to matplotlib which do not point to their most recent docs. This should be checked and fixed.

Seeing this now, it might be not so straightforward, because the old sites still exists.

For example, at the end of the notebook there is a link to https://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#axes-grid1
, but it should link to https://matplotlib.org/api/toolkits/axes_grid1.html.
