### ISSUE TITLE
Organizing slideshow cell properties for each notebook.

### ISSUE THREAD

**Issue by heistermann** [wradlib/wradlib-notebooks#23]
In the IPython notebook, you can set attributes to each cell the `Cell Toolbar`. Activating `View > Cell Toolbar > Slideshow`. After that, you can set, for each cell, its property in case the notebook is rendered as a slideshow. This can be done by

``` shell

$ ipython nbconvert notebook.ipynb --to slides

```

or in case the html slides shoudl be directly served:

``` shell

$ ipython nbconvert notebook.ipynb --to slides --post serve

```

Here's an [example](http://www.slideviper.oquanta.info/tutorial/slideshow_tutorial_slides.html#/).

We can set the slideshow attributes without affecting the remaining notebook functionality. This feature can be used to achieve a better presentability of the notebooks during courses/presentations. For this purpose, all cell properties need to be set in all notebooks. Sometimes this requires to rethink the internal organisation of the notebooks.

**Comment by kmuehlbauer** [comment]
I'm closing this. In recent times, we've created dedicated repos for short courses/conferences over at https://github.com/openradar. No immediate need to handle the maintenance burden here.
