### ISSUE TITLE
Is something wrong with the y and x axes?

### ISSUE THREAD

**Issue by syedhamidali** [wradlib/wradlib-notebooks#94]
What’s going on with the x and y axes? Are the ticks wrong or I’m missing something?

https://docs.wradlib.org/en/latest/notebooks/workflow/recipe2.html

![image](https://github.com/user-attachments/assets/a135c0e6-914b-4322-a419-f4539527675e)

**Comment by kmuehlbauer** [comment]
We use https://epsg.io/32632 in that example. So that's not a distance from the radar but the value for that projection (here in km).

**Comment by syedhamidali** [comment]
Okay, that makes sense.
